obstacle_range: 3.0
raytrace_range: 3.5   

robot_radius: 0.25

max_obstacle_height: 0.6
min_obstacle_height: 0.0
observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0}

# if set to false,then obstacle layer take unknow space to be free.
obstacle_layer:
   track_unknown_space: true
